"""CLI entrypoint for the test bot."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

from test_bot.discover import REPO_ROOT, Target, discover_targets
from test_bot.generate import generate_test_content, write_test_file
from test_bot.runner import run_single_app


def _git(*args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        cwd=REPO_ROOT,
        check=check,
        text=True,
        capture_output=True,
    )


def _run_tests_for_target(target: Target) -> None:
    run_single_app(target.language, target.app, target.app_dir, dry_run=False)


def _generate_and_verify(target: Target, *, max_attempts: int = 2) -> bool:
    fix_error: str | None = None
    for attempt in range(max_attempts):
        if attempt > 0 and target.test_path.is_file():
            target.test_path.unlink()
            print(f"Retrying {target.rel_source} (attempt {attempt + 1}) …")

        print(f"Generating tests for {target.rel_source} …")
        content = generate_test_content(target, fix_error=fix_error)
        write_test_file(target, content, dry_run=False)

        try:
            _run_tests_for_target(target)
            return True
        except subprocess.CalledProcessError as exc:
            fix_error = (exc.stderr or "") + (exc.stdout or "") or str(exc)
            print(f"Tests failed for {target.app_dir.name}:\n{fix_error[:2000]}")

    if target.test_path.is_file():
        target.test_path.unlink()
        print(f"Removed invalid test file {target.rel_test}")
    return False


PR_TITLE = "test-bot: add unit tests"


def _pr_body(targets_summary: str) -> str:
    return f"""## Summary

Automated unit tests generated by [test-bot](scripts/test-bot/README.md).

{targets_summary}

## Test plan

- [x] `test-bot` ran app test suites for affected projects
- [ ] Review generated tests for correctness and style
- [ ] PR Check workflow passes on this PR

---
*Workflow: `.github/workflows/test-bot.yml`*
"""


def _github_output(name: str, value: str) -> None:
    path = os.environ.get("GITHUB_OUTPUT")
    if not path:
        return
    with open(path, "a", encoding="utf-8") as handle:
        if "\n" in value:
            handle.write(f"{name}<<EOF\n{value}\nEOF\n")
        else:
            handle.write(f"{name}={value}\n")


def _push_branch(branch: str) -> None:
    _git("push", "-u", "origin", branch)


def _create_pull_request(
    branch: str,
    targets_summary: str,
) -> None:
    body = _pr_body(targets_summary)
    _push_branch(branch)

    if os.environ.get("GITHUB_ACTIONS", "").lower() == "true":
        _github_output("branch", branch)
        _github_output("pr_body", body)
        print(f"Pushed branch {branch}; workflow will open the PR.")
        return

    subprocess.run(
        [
            "gh",
            "pr",
            "create",
            "--title",
            PR_TITLE,
            "--body",
            body,
            "--head",
            branch,
            "--base",
            os.environ.get("TEST_BOT_BASE_BRANCH", "main"),
        ],
        cwd=REPO_ROOT,
        check=True,
        text=True,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="AI-sandbox test bot")
    parser.add_argument(
        "--max-targets",
        type=int,
        default=int(os.environ.get("TEST_BOT_MAX_TARGETS", "2")),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=os.environ.get("TEST_BOT_DRY_RUN", "").lower() in {"1", "true", "yes"},
    )
    args = parser.parse_args()

    targets = discover_targets(max_targets=args.max_targets)
    if not targets:
        print("No uncovered source files found in CI-covered apps.")
        return

    print("Targets:")
    for t in targets:
        print(f"  - {t.rel_source} -> {t.rel_test}")

    if args.dry_run:
        print("Dry run complete (discovery only; no LLM, commit, or PR).")
        return

    successful: list[Target] = []
    for target in targets:
        if _generate_and_verify(target):
            successful.append(target)

    if not successful:
        print("No tests were generated successfully.", file=sys.stderr)
        sys.exit(1)

    summary_lines = "\n".join(
        f"- `{t.rel_test}` (covers `{t.rel_source}`)" for t in successful
    )

    branch = f"test-bot/{datetime.now(UTC).strftime('%Y%m%d-%H%M%S')}"
    _git("config", "user.name", "github-actions[bot]")
    _git("config", "user.email", "github-actions[bot]@users.noreply.github.com")
    _git("checkout", "-b", branch)

    for target in successful:
        _git("add", target.test_path.relative_to(REPO_ROOT).as_posix())

    for language, app, app_dir in {(t.language, t.app, t.app_dir) for t in successful}:
        if language == "typescript":
            for name in ("package.json", "package-lock.json"):
                path = app_dir / name
                if path.is_file():
                    _git("add", path.relative_to(REPO_ROOT).as_posix())

    _git(
        "commit",
        "-m",
        "test-bot: add generated unit tests\n\n"
        + "\n".join(f"- {t.rel_test}" for t in successful),
    )

    _create_pull_request(branch, summary_lines)
    print(f"Opened PR from branch {branch} ({len(successful)} file(s))")


if __name__ == "__main__":
    main()
