"""CLI entrypoint for the test bot."""

from __future__ import annotations

import argparse
import os
import subprocess
from datetime import UTC, datetime
from pathlib import Path

from test_bot.discover import REPO_ROOT, discover_targets
from test_bot.generate import generate_test_content, write_test_file
from test_bot.runner import run_app_tests


def _git(*args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        cwd=REPO_ROOT,
        check=check,
        text=True,
        capture_output=True,
    )


def _create_pull_request(
    branch: str,
    targets_summary: str,
    *,
    dry_run: bool,
) -> None:
    title = "test-bot: add unit tests"
    body = f"""## Summary

Automated unit tests generated by [test-bot](scripts/test-bot/README.md).

{targets_summary}

## Test plan

- [x] `test-bot` ran app test suites for affected projects
- [ ] Review generated tests for correctness and style
- [ ] PR Check workflow passes on this PR

---
*Workflow: `.github/workflows/test-bot.yml`*
"""
    if dry_run:
        print(f"[dry-run] would open PR: {title}")
        print(body)
        return

    _git("push", "-u", "origin", branch)
    subprocess.run(
        [
            "gh",
            "pr",
            "create",
            "--title",
            title,
            "--body",
            body,
            "--head",
            branch,
            "--base",
            os.environ.get("TEST_BOT_BASE_BRANCH", "main"),
        ],
        cwd=REPO_ROOT,
        check=True,
        text=True,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="AI-sandbox test bot")
    parser.add_argument(
        "--max-targets",
        type=int,
        default=int(os.environ.get("TEST_BOT_MAX_TARGETS", "2")),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=os.environ.get("TEST_BOT_DRY_RUN", "").lower() in {"1", "true", "yes"},
    )
    args = parser.parse_args()

    targets = discover_targets(max_targets=args.max_targets)
    if not targets:
        print("No uncovered source files found in CI-covered apps.")
        return

    print("Targets:")
    for t in targets:
        print(f"  - {t.rel_source} -> {t.rel_test}")

    if args.dry_run:
        run_app_tests(targets, dry_run=True)
        print("Dry run complete (discovery only; no LLM, commit, or PR).")
        return

    for target in targets:
        print(f"Generating tests for {target.rel_source} …")
        content = generate_test_content(target)
        write_test_file(target, content, dry_run=False)

    run_app_tests(targets, dry_run=False)

    summary_lines = "\n".join(
        f"- `{t.rel_test}` (covers `{t.rel_source}`)" for t in targets
    )

    branch = f"test-bot/{datetime.now(UTC).strftime('%Y%m%d-%H%M%S')}"
    _git("config", "user.name", "github-actions[bot]")
    _git("config", "user.email", "github-actions[bot]@users.noreply.github.com")
    _git("checkout", "-b", branch)

    paths = sorted({t.test_path for t in targets})
    for path in paths:
        _git("add", path.relative_to(REPO_ROOT).as_posix())

    for _language, _app, app_dir in {(t.language, t.app, t.app_dir) for t in targets}:
        if _language == "typescript":
            for name in ("package.json", "package-lock.json"):
                path = app_dir / name
                if path.is_file():
                    _git("add", path.relative_to(REPO_ROOT).as_posix())

    _git(
        "commit",
        "-m",
        "test-bot: add generated unit tests\n\n"
        + "\n".join(f"- {t.rel_test}" for t in targets),
    )

    _create_pull_request(branch, summary_lines, dry_run=False)
    print(f"Opened PR from branch {branch}")


if __name__ == "__main__":
    main()
